export const DUMMY_PROFILES = [
  {
    id: 'dummy-1',
    name: 'Aishwarya R',
    age: 26,
    height_cm: 165,
    city: 'Chennai',
    state: 'Tamil Nadu',
    education: 'B.Tech IT',
    profession: 'Software Engineer',
    income_lpa: 12,
    caste: 'Saiva vellalar',
    religion: 'Hindu',
    mother_tongue: 'Tamil',
    photo_url: 'https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    photos: [],
    bio: 'Looking for a supportive and understanding partner. I love traveling, reading, and exploring new cuisines.',
    marital_status: 'never_married',
    physical_status: 'Normal',
    last_active: new Date().toISOString(),
  },
  {
    id: 'dummy-2',
    name: 'Karthik S',
    age: 29,
    height_cm: 178,
    city: 'Bangalore',
    state: 'Karnataka',
    education: 'MBA',
    profession: 'Marketing Manager',
    income_lpa: 18,
    caste: 'Agam udaiyar',
    religion: 'Hindu',
    mother_tongue: 'Tamil',
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    photos: [],
    bio: 'Career-oriented but value family above all. Enjoy weekend treks and photography.',
    marital_status: 'never_married',
    physical_status: 'Normal',
    last_active: new Date().toISOString(),
  },
  {
    id: 'dummy-3',
    name: 'Priya K',
    age: 27,
    height_cm: 160,
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    education: 'M.Sc Mathematics',
    profession: 'Professor',
    income_lpa: 8,
    caste: 'Sengundhar mudhaliar',
    religion: 'Hindu',
    mother_tongue: 'Tamil',
    photo_url: 'https://images.unsplash.com/photo-1610473268487-1901ddc1e5cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    photos: [],
    bio: 'Simple, traditional, and family-oriented. Looking for someone with strong moral values.',
    marital_status: 'never_married',
    physical_status: 'Normal',
    last_active: new Date().toISOString(),
  },
  {
    id: 'dummy-4',
    name: 'Vikram N',
    age: 31,
    height_cm: 182,
    city: 'Chennai',
    state: 'Tamil Nadu',
    education: 'MS Computer Science',
    profession: 'Data Scientist',
    income_lpa: 25,
    caste: 'Thuluva Vellalar',
    religion: 'Hindu',
    mother_tongue: 'Tamil',
    photo_url: 'https://images.unsplash.com/photo-1550920409-913bc58742fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    photos: [],
    bio: 'Tech enthusiast. Returned from US last year. Love playing badminton and watching movies.',
    marital_status: 'never_married',
    physical_status: 'Normal',
    last_active: new Date().toISOString(),
  },
  {
    id: 'dummy-5',
    name: 'Meenakshi T',
    age: 25,
    height_cm: 163,
    city: 'Madurai',
    state: 'Tamil Nadu',
    education: 'MBBS',
    profession: 'Doctor',
    income_lpa: 15,
    caste: 'Agam udaiyar',
    religion: 'Hindu',
    mother_tongue: 'Tamil',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    photos: [],
    bio: 'Passionate about medicine and helping people. Hoping to find someone who respects my career.',
    marital_status: 'never_married',
    physical_status: 'Normal',
    last_active: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'dummy-6',
    name: 'Arjun V',
    age: 33,
    height_cm: 175,
    city: 'Pune',
    state: 'Maharashtra',
    education: 'B.E Mechanical',
    profession: 'Entrepreneur',
    income_lpa: 35,
    caste: 'Saiva vellalar',
    religion: 'Hindu',
    mother_tongue: 'Tamil',
    photo_url: 'https://images.unsplash.com/photo-1600486913747-55e5470d6f40?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    photos: [],
    bio: 'Running my own startup. Looking for a partner who is driven and independent.',
    marital_status: 'divorced',
    physical_status: 'Normal',
    last_active: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'dummy-7',
    name: 'Lakshmi P',
    age: 28,
    height_cm: 158,
    city: 'Trichy',
    state: 'Tamil Nadu',
    education: 'B.Com',
    profession: 'Banker',
    income_lpa: 9,
    caste: 'Sengundhar mudhaliar',
    religion: 'Hindu',
    mother_tongue: 'Tamil',
    photo_url: 'https://images.unsplash.com/photo-1627993077395-e21fcb6121b6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    photos: [],
    bio: 'Friendly and easy-going. Love spending time with family and cooking traditional dishes.',
    marital_status: 'never_married',
    physical_status: 'Normal',
    last_active: new Date().toISOString(),
  },
  {
    id: 'dummy-8',
    name: 'Siddharth M',
    age: 30,
    height_cm: 177,
    city: 'Hyderabad',
    state: 'Telangana',
    education: 'M.Tech',
    profession: 'Cloud Architect',
    income_lpa: 22,
    caste: 'Thuluva Vellalar',
    religion: 'Hindu',
    mother_tongue: 'Tamil',
    photo_url: 'https://images.unsplash.com/photo-1542156822-6924d1a71ace?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    photos: [],
    bio: 'Fun loving and adventurous. Enjoy road trips and listening to classic rock.',
    marital_status: 'never_married',
    physical_status: 'Normal',
    last_active: new Date().toISOString(),
  },
  {
    id: 'dummy-9',
    name: 'Nandini R',
    age: 26,
    height_cm: 168,
    city: 'Chennai',
    state: 'Tamil Nadu',
    education: 'B.Arch',
    profession: 'Architect',
    income_lpa: 14,
    caste: 'Agam udaiyar',
    religion: 'Hindu',
    mother_tongue: 'Tamil',
    photo_url: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    photos: [],
    bio: 'Creative soul. Passionate about art and design. Looking for a partner with a good sense of humor.',
    marital_status: 'never_married',
    physical_status: 'Normal',
    last_active: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'dummy-10',
    name: 'Rahul C',
    age: 32,
    height_cm: 180,
    city: 'Chennai',
    state: 'Tamil Nadu',
    education: 'CA',
    profession: 'Chartered Accountant',
    income_lpa: 28,
    caste: 'Saiva vellalar',
    religion: 'Hindu',
    mother_tongue: 'Tamil',
    photo_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    photos: [],
    bio: 'Financially independent and responsible. Looking for someone who values transparency and trust.',
    marital_status: 'never_married',
    physical_status: 'Normal',
    last_active: new Date().toISOString(),
  }
];
